### PR TITLE
Fix a few typos, add my printing changes

### PR DESCRIPTION
**Pull request by DevinR528**
Some of the spelling fixes would be in a real PR but this is only to try and figure out #13

### CODE REVIEW

**Review by xFrednet — COMMENTED** [review]
Thank you for the PR, I'm happy to see some action. If you have a rough code overview I can also assign my next PRs to you :)


I hope that these comments aren't too nit-picky. We can obviously still change the API during initial development. I haven't tested the change jet. I hope that I can make some progress on this tomorrow.

**Comment by DevinR528** [comment]
Sorry I wasn't more clear, I just meant this to be a diff so we could hopefully reproduce my error.

I started with trying to hook into rustc's error reporting but since I couldn't get it to run without the error I just pushed what I had. Once I get the error figured out I'll use your feedback to shape a new PR!

**Comment by xFrednet** [comment]
Ahh, sorry for the confusion. The title gave me the expression, that this was an actual PR. I'll check these changes out. :upside_down_face:

**Comment by DevinR528** [comment]
Yeah, upon rereading, that's where I should have put the "ignore as PR", no worries though it's not like I won't use the feedback. If we could hold off on closing this PR so I can easily check it that'd be cool.

**Pull request closed without merging**
