### PR TITLE
0019 basic UI tests

### LINKED ISSUE #19: Add UI test support for lints
Clippy and Rustc both use ui test to test lints. These tests run the compiler on test files and compares the output to a `.stderr` file that is stored next to the save file.

* See Clippy's test directory as an example: https://github.com/rust-lang/rust-clippy/blob/master/tests/ui
* See Clippy's documentation: https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#testing
* Rustc's documentation: https://rustc-dev-guide.rust-lang.org/tests/ui.html#ui-tests

Dynlint has an extra [dylint_testing](https://crates.io/crates/dylint_testing/2.0.2) crate, which is smart and something I believe worth aiming for.

Currently, there are two major ui test crates [trybuild](https://crates.io/crates/trybuild) and [compiletest_rs](https://crates.io/crates/compiletest_rs). From these, I like the interface of `trybuild` more, as it's simpler. However, it lacks some customizability, which is required lints. Clippy therefore uses compiletest_rs. See Clippy's [`compile-test.rs` file](https://github.com/rust-lang/rust-clippy/blob/master/tests/compile-test.rs)

It's also worth noting, that both ui crates use rustc internally. This means that ui tests using these crates require us to use the rustc lint driver for tests. For now, I think this is fine, but we might want to ensure that our testing crate doesn't expose the specific driver :)

### PR DESCRIPTION
**Pull request by xFrednet**
This PR adds UI tests for our `linter_lints` lint crate. For now, it's just a configured `compiletest_rs`. In the future, we should probably consider creating our own test crate, like `dylint` does. See [dylint_testing](https://crates.io/crates/dylint_testing). For now, I feel like our API, way of loading lints etc is too unstable for that. Especially since we might need to rework how lint crates are loaded in the future #8. As long as we have no external users, I believe this is a good solution.

To run all UI tests you can just use `cargo uitest` in the workspace root. Specific test files can be specified with the `TESTNAME` environment value like this `TESTNAME=find_static cargo uitest`. The tests can also be blessed with the `BLESS` environment value. Updating an output file is as simple as running `BLESS=1 cargo uitest`. Both environment values can be combined. :)

@DevinR528 Would you mind reviewing this? It's also fine, if you don't have the time. I don't want to flood you with PRs. :upside_down_face: 

---

Closes #19 (For now, I will probably create an issue, to create a proper testing crate for external tests)

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey @DevinR528, some changes I plan to work on next will probably depend on this. Could you review this?

While a second pair of eyes is always better, I would also be okay with merging this as it is. Most of this will be reworked, when we create a testing framework for external linting crates (even if the setup idea might stay the same). So if you don't have the time, that's totally fine :)

**Review by DevinR528 — APPROVED** [review]
Sorry that took so long, working on llvm all day long then trying to have any motivation to do anything after work is hard!

Everything looks good to me! Great to have this feature from the start.

**Comment by xFrednet** [comment]
Thank you very much for the review. Being motivated to do more coding can be hard. Working on LLVM sound like a lot of fun, but exhausting simultaneously.

If you currently don't have as much time, I'm also okay with merging these PRs without a proper review. Currently, I'm mostly experimenting with different representations and translating the Rust reference. I feel like this is not as critical and interesting to review.

There are some design related topics, which I'm currently looking into. I plan to create related issues in the design repo to get feedback, before working on the implementation.

**Comment by DevinR528** [comment]
I don't mind reviewing as long as your fine with a few days in between. now that I am settled I feel like I'll have more energy and time in my routine to work on this and other personal projects!

**Comment by xFrednet** [comment]
Happy to hear that you're settling in. In that case, I think we should for now continue like this and see how it goes. I'm also focussing on finishing some older projects to fully focus on this one.

**Pull request merged**
